In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score

In [2]:
df = pd.read_csv('creditcard.csv')

In [3]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [4]:
# checking the number of missing values

df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [5]:
# distribution of legit and fraudulent transactions

df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

# The dataset is highly imbalanced
0 -> normal transaction ,
1 -> fraud transaction

In [6]:
# separating data for analysis

legit =df[df.Class == 0]
fraud = df[df.Class == 1]

In [7]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [8]:
# Statistical measures of the data 

legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [9]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [10]:
# Compare the values for both the transactions

df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

# Under Sampling
Build a sample dataset containing simlar distribution of normal and fraudulent transactions

In [11]:
legit_sample = legit.sample(n = 492)

# conat two dataframes

new_dataset = pd.concat([legit_sample,fraud],axis = 0)

In [12]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
205052,135571.0,-0.126221,1.136682,0.350904,1.028930,0.676846,0.049309,0.647720,-0.415273,-0.257333,...,-0.010976,0.264152,-0.084583,0.583598,-0.785411,0.712610,-0.378315,0.035265,13.54,0
257125,158012.0,2.068040,-0.854566,-1.484383,-0.952949,-0.293970,-0.761562,-0.172659,-0.295966,-0.858394,...,0.111625,0.234896,0.078932,-0.357476,-0.007348,-0.282854,-0.047392,-0.064132,76.48,0
227720,145191.0,1.451416,-1.911941,-1.594898,-0.451520,-0.967156,-1.051620,0.231475,-0.472198,-0.447226,...,0.213358,-0.165358,-0.110698,0.022953,-0.216525,-0.367303,-0.098557,0.007252,399.00,0
121024,76047.0,1.307464,-1.456651,-0.388390,-1.594207,-0.776065,0.247155,-0.777301,-0.081745,-1.826194,...,-0.189703,-0.434661,-0.240574,-1.342537,0.471022,-0.099160,0.014653,0.026776,154.50,0
97299,66155.0,-0.463069,1.083919,1.721463,0.046252,-0.116113,-1.082799,0.758765,-0.139773,-0.561858,...,-0.191444,-0.457629,0.017685,0.718540,-0.202718,0.047688,0.270174,0.127227,4.49,0

In [13]:
new_dataset['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [14]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,95846.203252,-0.000874,-0.182699,0.023079,-0.002249,0.004764,-0.081332,0.109507,0.013819,-0.014819,...,0.082162,-0.025841,-0.017635,-0.015749,-0.001946,-0.019423,-0.033376,0.017072,0.007261,113.991890
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

# Spliting the data

In [15]:
X = new_dataset.drop(columns = 'Class',axis = 1)
y = new_dataset['Class']

In [19]:
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size = 0.2,random_state = 2,stratify =y
)

In [20]:
print(X.shape,X_train.shape,X_test.shape)

(984, 30) (787, 30) (197, 30)

# Model Training

Logistic Regression Model

In [31]:
model = LogisticRegression()
model.fit(X_train,y_train)

C:\Users\V.Bhargav\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

# Model Evaluation

In [28]:
# Accuracy Score for training data

X_train_pred = model.predict(X_train)
train_acc = accuracy_score(X_train_pred,y_train)
print(train_acc)

0.9428208386277002

In [29]:
# Accuracy Score for test data

y_pred = model.predict(X_test)
test_acc = accuracy_score(y_pred,y_test)
print(test_acc)

0.9238578680203046